### ISSUE TITLE
Image size

### ISSUE THREAD

**Issue by tibastral** [inuitcss/objects.flag#9]
Hello everyone, hello Harry,

I was asking why images aren't width 100% when responsive, or at least why they aren't centered.

And also, wouldn't it be nice to have an image with a defined max-width, in order to be able to put bigger images without them to be huge in the desktop version ?

Thank you for your amazing work,

Something like :

``` scss
@include media-query('palm') {
  .flag__img > img {
    width: 100%
  }
}

.flag__img > img {
  max-width: 200px;
}

```

I also don't understand why the $inuit-flag-collapse-at is not by default the 'palm' size.

Have a great day

\- Thibaut

**Comment by florianbouvot** [comment]
@tibastral overall, I think these options are too specific to be treated at objects level.

For basic use I set a fixed width to the image like so :

``` html
...
<div class="flag__img">
    <img width="200" src="path/to/my/image.jpg" alt="">
</div>
...
```

For advanced use I create components to fit my UI needs like so :

HTML

``` html
<div class="avatar flag">
    <div class="flag__img">
        <img class="avatar__img" src="path/to/my/image.jpg" alt="">
    </div>
...
```

CSS

``` css
.avatar__img
    max-width: 200px;

    @include media-query('palm') {
        width: 100%;
    }
}
```
